package hibernateDataFiles;
// Generated Jul 5, 2018 8:37:29 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CategoriesAnswers generated by hbm2java
 */
@Entity
@Table(name = "categories_answers", schema = "edi_ms")
public class CategoryAnswer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private CategoryAnswerId id;
	private CategoryIgnoreJson category;
	private Survey survey;
	private long grade;
	private String comment;

	public CategoryAnswer() {
	}

	public CategoryAnswer(CategoryAnswerId id, CategoryIgnoreJson category, Survey survey, long grade) {
		this.id = id;
		this.category = category;
		this.survey = survey;
		this.grade = grade;
	}

	public CategoryAnswer(CategoryAnswerId id, CategoryIgnoreJson category, Survey survey, long grade, String comment) {
		this.id = id;
		this.category = category;
		this.survey = survey;
		this.grade = grade;
		this.comment = comment;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "surveyId", column = @Column(name = "survey_id", nullable = false)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)) })

	public CategoryAnswerId getId() {
		return this.id;
	}

	public void setId(CategoryAnswerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false, insertable = false, updatable = false)
	public CategoryIgnoreJson getCategory() {
		return this.category;
	}

	public void setCategory(CategoryIgnoreJson category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "survey_id", nullable = false, insertable = false, updatable = false)
	@JsonIgnore
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@Column(name = "grade", nullable = false)
	public long getGrade() {
		return this.grade;
	}

	public void setGrade(long grade) {
		this.grade = grade;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
