package hibernateDataFiles;
// Generated Jul 5, 2018 8:37:29 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriesAnswersId generated by hbm2java
 */
@Embeddable
public class CategoryAnswerId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long surveyId;
	private long categoryId;

	public CategoryAnswerId() {
	}
	

	public CategoryAnswerId(long surveyId, long categoryId) {
		this.surveyId = surveyId;
		this.categoryId = categoryId;
	}

	@Column(name = "survey_id", nullable = false)

	public long getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(long surveyId) {
		this.surveyId = surveyId;
	}

	@Column(name = "category_id", nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryAnswerId))
			return false;
		CategoryAnswerId castOther = (CategoryAnswerId) other;

		return (this.getSurveyId() == castOther.getSurveyId()) && (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSurveyId();
		result = 37 * result + (int) this.getCategoryId();
		return result;
	}

}
