	package hibernateDataFiles;
// Generated Jul 5, 2018 8:37:29 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MembersAnswersId generated by hbm2java
 */
@Embeddable
public class MemberAnswerId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long surveyId;
	private long questionId;

	public MemberAnswerId() {
	}

	public MemberAnswerId(long surveyId, long questionId) {
		this.surveyId = surveyId;
		this.questionId = questionId;
	}

	@Column(name = "survey_id", nullable = false)
	public long getSurveyId() {
		return this.surveyId;
	}

	public void setSurveyId(long surveyId) {
		this.surveyId = surveyId;
	}

	@Column(name = "question_id", nullable = false)
	public long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(long questionId) {
		this.questionId = questionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemberAnswerId))
			return false;
		MemberAnswerId castOther = (MemberAnswerId) other;

		return (this.getSurveyId() == castOther.getSurveyId()) && (this.getQuestionId() == castOther.getQuestionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSurveyId();
		result = 37 * result + (int) this.getQuestionId();
		return result;
	}

}
