package hibernateDataFiles;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PossibleAnswers generated by hbm2java
 */
@Entity
@Table(name = "possible_answers", schema = "edi_ms")
public class PossibleAnswerIgnoreJson implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long possibleAnswerId;
	private QuestionIgnoreJson questionIgnoreJson;
	private String answerValue;
	private Date effectiveDate;
	private Date expirationDate;
	private String createdBy;
		private Date updateDate;
	private String updatedBy;
//	private Set<MembersAnswers> membersAnswerses = new HashSet<MembersAnswers>(0);

	public PossibleAnswerIgnoreJson() {
	}

	public PossibleAnswerIgnoreJson(long possibleAnswerId, QuestionIgnoreJson questionIgnoreJson, String answerValue) {
		this.possibleAnswerId = possibleAnswerId;
		this.questionIgnoreJson = questionIgnoreJson;
		this.answerValue = answerValue;
	}

//	public PossibleAnswers(long possibleAnswerId, questionIgnoreJsons questionIgnoreJsons, String answerValue, Date effectiveDate,
//			Date expirationDate, Set<MembersAnswers> membersAnswerses) {
//		this.possibleAnswerId = possibleAnswerId;
//		this.questionIgnoreJsons = questionIgnoreJsons;
//		this.answerValue = answerValue;
//		this.effectiveDate = effectiveDate;
//		this.expirationDate = expirationDate;
//		this.membersAnswerses = membersAnswerses;
//	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "possible_answer_id")
	@SequenceGenerator(allocationSize = 1, name = "possible_answer_id", sequenceName = "EDI_MS.answer_seq_id_seq")
	
	@Column(name = "possible_answer_id", unique = true, nullable = false)
	public long getPossibleAnswerId() {
		return this.possibleAnswerId;
	}

	public void setPossibleAnswerId(long possibleAnswerId) {
		this.possibleAnswerId = possibleAnswerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", nullable = false)
	@JsonIgnore
 	public QuestionIgnoreJson getQuestionIgnoreJson() {
		return this.questionIgnoreJson;
	}

	public void setQuestionIgnoreJson(QuestionIgnoreJson questionIgnoreJson) {
		this.questionIgnoreJson = questionIgnoreJson;
	}

	@Column(name = "answer_value", nullable = false, length = 50)
	public String getAnswerValue() {
		return this.answerValue;
	}

	public void setAnswerValue(String answerValue) {
		this.answerValue = answerValue;
	}

//	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date", length = 13)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

//	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 13)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}
	
	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "update_date", length = 13)
	public Date getUpdateDate() {
		return updateDate;
	}

	
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "updated_by", length = 20)
	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}



//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "possibleAnswers")
//	public Set<MembersAnswers> getMembersAnswerses() {
//		return this.membersAnswerses;
//	}

//	public void setMembersAnswerses(Set<MembersAnswers> membersAnswerses) {
//		this.membersAnswerses = membersAnswerses;
//	}

}
